### ISSUE TITLE
I can not login

### ISSUE THREAD

**Issue by mijailn** [mgp25/WhatsAPI-Official#394]
Can you help me,

sends me an error every time I try to login
```xml
[root@mail examples]# php exampleFunctional.php
[] Logging in as 'mijail' (52552427xxxx)
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="52552427xxxx"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>▒XcI5▒#i▒60▒:▒e&b▒</challenge>

tx  <response>3▒
▒D▒▒O▒>syP▒*▒#▒)
~F3▒▒4▒P/▒</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'Exception' with message 'Login Failure' in /root/WhatsAPI-Official/src/whatsprot.class.php:2285
Stack trace:
#0 /root/WhatsAPI-Official/src/whatsprot.class.php(606): WhatsProt->doLogin()
#1 /root/WhatsAPI-Official/examples/exampleFunctional.php(70): WhatsProt->loginWithPassword('wD7OITh8mSYbrYW...')
#2 {main}
  thrown in /root/WhatsAPI-Official/src/whatsprot.class.php on line 2285
```

**Comment by devengandre** [comment]
There is an issue with your device user agent. Make copy of your /src/whatsprot.class.php class in separate folder and change following keys as below and include updated file in your code instead of original one. (for login and message sending purpose only):

const WHATSAPP_DEVICE = 'Android';                      // The device name.
const WHATSAPP_VER = '2.11.505';                // The WhatsApp version.
const WHATSAPP_USER_AGENT = 'WhatsApp/2.11.505 Android/4.3 Device/GalaxyS3'; // User agent used in request/registration code.

For registration, use original class file. 

/* Hope this solves your problem */

-Dev

**Comment by mgp25** [comment]
@mijailn are you using WhatsAPI Official code? If you are, then the node you received:

```xml
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

Means your number its blocked.

You can find more info in the F.A.Q: https://github.com/mgp25/WhatsAPI-Official/wiki/Frequently-asked-questions

Regards
