### ISSUE TITLE
Up-gradation of whatsaprot class

### ISSUE THREAD

**Issue by rajenpal033** [mgp25/WhatsAPI-Official#465]
Hello,

I was using the files of old WhatsAPI ( Venom ) and also I changes the class on few places, adding few custom functions etc. now I want to upgrade my files to this WhatsAPI-Official files, but actually I want to merge all my previous customization on whatsprot.class.php, is there any easy way to do this?

Thanks & Regards.

**Comment by archergod** [comment]
Copy paste is always easy? 

Venom API is quite old and has major changes since then, one of major change is file structure change. And probably some of new functions are already there in this new API, so read it carefully and then make your migration plan on what function you should upgrade and not. We cannot help here as it is specific to your project and you have to decide it yourself.

there is no shortcut here. I did migration and hence can tell this,

**Comment by rajenpal033** [comment]
okay thank you actually the problem is I had done several changes since past few months and can not remember the places where I did and my total project will be screwed if I change the old files but I was just think it's always good to have updated functions and files. that's it.

**Comment by archergod** [comment]
not sure which version you are using, but in oct last year some API upgrade happen in WhatsAPP and now they introduce voice call, blue tick so it is better to upgrade your code.
