### ISSUE TITLE
Number blocked

### ISSUE THREAD

**Issue by thetitoo** [mgp25/WhatsAPI-Official#473]
First: I'm not spamming, not broadcasting. This is not for complain neither.

1. I have been using a number in my staging server that is running perfectly.
2. I had another number for my production server. 

Once I setup the number for my production server it got automatically permanently blocked.
I realize that I was still using the same number on my phone at the same time. 

Since the number is being used at the same time on 2 different devices, I'm assuming that is the reason it has been blocked.

Is there any way to confirm this?

**Comment by mgp25** [comment]
You cant use the same number with the API and with your device at the same time, otherwise the password will be changing and you cant use it for WhatsAPI. 

You can extract your password from your device and use that password to login with WhatsAPI.

More info in the wiki: https://github.com/mgp25/WhatsAPI-Official/wiki

Regards
