### ISSUE TITLE
my numbers get banned

### ISSUE THREAD

**Issue by hey-there** [mgp25/WhatsAPI-Official#590]
Hello,

All my numbers get instantly banned after registration (INSTANT!). Try'd different countrys (austria, belgium...)  all time the same.  - not-authorized

Any Ideas? Script runs on localhost & I register my numbers with WART and try to Login with
Ofcourse i have try it with changing my ip... but nothing new.

```php
	$data = $king->getWhatsNumber();
	print_r($data);
	$w = new WhatsProt($data["number"], $data["name"], $data["password"], true);
	$w->connect();
	$w->loginWithPassword($data["password"]);
 ```

Also try'd this (maybe the data type from db the error i thought):
```php
	$w = new WhatsProt("4915735982436", "Peer", "OJixlyjIzFCuAVr4xBkZGLp29x4=", true);
	$w->connect();
	$w->loginWithPassword("OJixlyjIzFCuAVr4xBkZGLp29x4=");
```

Greetings

**Comment by mgp25** [comment]
@hey-there 

1- You are initializing wrong the WhatsProt, read the [wiki](https://github.com/mgp25/WhatsAPI-Official/wiki)
2- Password is not the identity, and look for what i said in 1

If you are getting banned in localhost. Could be:

You are spamming or sending massive requests and WhatsApp blocked your IP. By sending massive requests i mean requestiong too much `last seen`,  profile images or even sending messages.

Or

You are using an outdated code and thats why you arre getting blocked directly, please update your code and read the wiki in order to use the code in the proper way.

Regards
